### ISSUE TITLE
Requesting the release of the code

### ISSUE THREAD

**Issue by Mona-ShZeinoddin** [IRMVLab/DDS-SLAM#1]
Hello!

Congratulations on your amazing work!

I am really looking forward to trying out your method on my data, I was wondering if and when do you plan to release your code? would be very grateful for any updates.

**Comment by Mar-lll** [comment]
Thank you for your interest in our work. The code will be released within a month.

**Comment by Mona-ShZeinoddin** [comment]
Hello!

Just wanted to follow up with my openned issue.

Would be very grateful for your help
